# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - none

pool: $(agent_pool_name)

variables:
  - group: "Variable Group"
  - name: dockerfilePath
    value: '$(Build.SourcesDirectory)/app/Dockerfile'
  - name: tag
    value: '$(Build.BuildId)'

stages:
- stage: Build_and_push
  jobs:
  - job: Build_and_push
    displayName: Build and push Docker image
    steps:
    - task: DockerInstaller@0
      displayName: Install Docker
      inputs:
        dockerVersion: '17.09.0-ce'
    - task: Docker@2
      enabled: true
      displayName: Build and push an image to Azure container registry
      inputs:
        command: buildAndPush
        repository: $(project_name)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(docker_registry_sc_name)
        tags: |
          $(tag)
    - task: AzureCLI@2
      enabled: true
      displayName: Push Docker image from ACR to ACI
      inputs:
        azureSubscription: '$(az_sc_name)'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $img = "$(acr_url)/$(project_name):$(tag)"
          Write-Host $img
          az container create --resource-group $(az_rg_name) --name $(project_name) --image $img --registry-login-server $(acr_url) --registry-password $(acr_pwd) --registry-username $(acr_user) --os-type Linux --restart-policy OnFailure
